### ISSUE TITLE
Unexpected input 'options'

### ISSUE THREAD

**Issue by maelchiotti** [Minionguyjpro/Inno-Setup-Action#1]
Hi, when using your action exactly as indicated, I get the following warning:

```bash
Warning: Unexpected input(s) 'options', valid inputs are ['path']
```

My job:

```yaml
- name: Run InnoSetup
  uses: Minionguyjpro/Inno-Setup-Action@v1.0.0
  with:
    path: app.iss
    options: /O+
```

It still works and builds my app but I'm wondering if the options work at all?
