### ISSUE TITLE
Feat: support unofficial languages

### ISSUE THREAD

**Issue by KeJunMao** [Minionguyjpro/Inno-Setup-Action#99]
For example, I want to install Chinese Simplified language, how do I configure it?

https://raw.githubusercontent.com/jrsoftware/issrc/main/Files/Languages/Unofficial/ChineseSimplified.isl

**Comment by DuckDuckStudio** [comment]
Hi @KeJunMao ,
I used this step to configure unofficial language files before building the installer:

```yml
jobs:
  auto-pack-releases:
    runs-on: windows-latest

    steps:

        # More steps, see https://github.com/DuckDuckStudio/Fufu_Dev_Tools/blob/main/.github/workflows/auto-pack-releases.yml

      - name: 配置 Inno 中文翻译
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/jrsoftware/issrc/main/Files/Languages/Unofficial/ChineseSimplified.isl" -OutFile "C:\Program Files (x86)\Inno Setup 6\Languages\ChineseSimplified.isl"

      - name: 构建安装程序
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
        with:
          path: pack.iss
          options: /O+
```

It works in [version 1.2.4](https://github.com/Minionguyjpro/Inno-Setup-Action/releases/tag/v1.2.4).

**Comment by KeJunMao** [comment]
Thanks for the quick reply!

A simpler scenario

```yml
- name: Compile .ISS to .EXE Installer
  shell: bash
  if: ${{ runner.os == 'Windows' }}
  run: |
    curl -k -O https://raw.githubusercontent.com/jrsoftware/issrc/main/Files/Languages/Unofficial/ChineseSimplified.isl
    mv ChineseSimplified.isl "C:\Program Files (x86)\Inno Setup 6\Languages"
    iscc clipturbo.iss
```
